
(COMMENT THIS IS THE RABBIT LISP CODE FOR "rabbit/fib.scm") 

(DECLARE (SPECIAL **CONT** **ONE** **TWO** **THREE** **FOUR** **FIVE**
		  **SIX** **SEVEN** **EIGHT** **ENV** **FUN** **NARGS**)) 
(PROGN (QUOTE COMPILE) (COMMENT MODULE FOR FUNCTION FIB)
       (DEFUN |rabbit/fib-92| NIL
	 (PROG NIL (DECLARE (SPECIAL |rabbit/fib-92|))
	       (GO (PROG2 NIL (CAR **ENV**) (SETQ **ENV** (CDR **ENV**))))
	       F-91 (COMMENT (DEPTH = 0) (FNP = NIL) (VARS = (CONT-88 N)))
	       (COND ((< **ONE** (QUOTE 2))
		      (SETQ **FUN** **CONT**)
		      (RETURN NIL))
		     (T
		      ((LAMBDA (Q-93 Q-94)
			       (SETQ **ONE** Q-94)
			       (SETQ **CONT** Q-93))
		       (CONS (QUOTE CBETA)
			     (CONS |rabbit/fib-92|
				   (CONS (QUOTE C-90)
					 (CONS **ONE**
					       (CONS **CONT** **ENV**)))))
		       (- **ONE** (QUOTE 1)))
		      (GO F-91)))
	       C-90 (COMMENT (DEPTH = 0) (FNP = NIL) (ENV = (N CONT-88)))
	       ((LAMBDA (Q-95 Q-96)
			(SETQ **ONE** Q-96)
			(SETQ **CONT** Q-95))
		(CONS (QUOTE CBETA)
		      (CONS |rabbit/fib-92|
			    (CONS (QUOTE C-89)
				  (CONS **ONE** **ENV**))))
		(- (CAR **ENV**) (QUOTE 2)))
	       (SETQ **ENV** (CDDDR FIB))
	       (GO F-91)
	       C-89 (COMMENT (DEPTH = 0) (FNP = NIL) (ENV = (NODE-78 N CONT-88)))
	       (SETQ **FUN** (CADDR **ENV**))
	       (SETQ **ONE** (+ (CAR **ENV**) **ONE**))
	       (RETURN NIL)))
       (SETQ |rabbit/fib-92| (GET (QUOTE |rabbit/fib-92|) (QUOTE EXPR)))
       (SETQ FIB (LIST (QUOTE CBETA) |rabbit/fib-92| (QUOTE F-91)))
       (DEFPROP |rabbit/fib-92| FIB USER-FUNCTION)) 
(PROGN (QUOTE COMPILE) (COMMENT MODULE FOR FUNCTION |init-rabbit/fib|)
       (DEFUN |rabbit/fib-102| NIL
	 (PROG NIL (DECLARE (SPECIAL |rabbit/fib-102|))
	       (GO (PROG2 NIL (CAR **ENV**) (SETQ **ENV** (CDR **ENV**))))
	       F-101 (COMMENT (DEPTH = 0) (FNP = NIL) (VARS = (CONT-100)))
	       (SETQ **FUN** **CONT**)
	       (SETQ **ONE** (QUOTE NIL))
	       (RETURN NIL)))
       (SETQ |rabbit/fib-102| (GET (QUOTE |rabbit/fib-102|) (QUOTE EXPR)))
       (SETQ |init-rabbit/fib| (LIST (QUOTE CBETA) |rabbit/fib-102| (QUOTE F-101)))
       (DEFPROP |rabbit/fib-102| |init-rabbit/fib| USER-FUNCTION)) 
(COMMENT (COMPILE TIME 5 SECONDS)) 
